// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: demo/v1/orders.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Orders_GetOrder_FullMethodName     = "/demo.v1.Orders/GetOrder"
	Orders_ListOrders_FullMethodName   = "/demo.v1.Orders/ListOrders"
	Orders_CreateOrders_FullMethodName = "/demo.v1.Orders/CreateOrders"
	Orders_Fail_FullMethodName         = "/demo.v1.Orders/Fail"
)

// OrdersClient is the client API for Orders service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Orders is the toy service Mirador is developed and demoed against. Its
// methods exist to produce the four shapes a gRPC proxy has to survive: a
// plain unary call, a server stream, a client stream, and a failure that
// answers with a non-zero status and no message at all.
type OrdersClient interface {
	// Unary, succeeds.
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*Order, error)
	// Server streaming: several response messages on one call.
	ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Order], error)
	// Client streaming: several request messages on one call.
	CreateOrders(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Order, CreateOrdersSummary], error)
	// Answers with the requested status code and no body, which is the
	// trailers-only response that carries the status in the headers instead
	// of the trailers.
	Fail(ctx context.Context, in *FailRequest, opts ...grpc.CallOption) (*Order, error)
}

type ordersClient struct {
	cc grpc.ClientConnInterface
}

func NewOrdersClient(cc grpc.ClientConnInterface) OrdersClient {
	return &ordersClient{cc}
}

func (c *ordersClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*Order, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Order)
	err := c.cc.Invoke(ctx, Orders_GetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordersClient) ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Order], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Orders_ServiceDesc.Streams[0], Orders_ListOrders_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListOrdersRequest, Order]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Orders_ListOrdersClient = grpc.ServerStreamingClient[Order]

func (c *ordersClient) CreateOrders(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Order, CreateOrdersSummary], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Orders_ServiceDesc.Streams[1], Orders_CreateOrders_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Order, CreateOrdersSummary]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Orders_CreateOrdersClient = grpc.ClientStreamingClient[Order, CreateOrdersSummary]

func (c *ordersClient) Fail(ctx context.Context, in *FailRequest, opts ...grpc.CallOption) (*Order, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Order)
	err := c.cc.Invoke(ctx, Orders_Fail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrdersServer is the server API for Orders service.
// All implementations must embed UnimplementedOrdersServer
// for forward compatibility.
//
// Orders is the toy service Mirador is developed and demoed against. Its
// methods exist to produce the four shapes a gRPC proxy has to survive: a
// plain unary call, a server stream, a client stream, and a failure that
// answers with a non-zero status and no message at all.
type OrdersServer interface {
	// Unary, succeeds.
	GetOrder(context.Context, *GetOrderRequest) (*Order, error)
	// Server streaming: several response messages on one call.
	ListOrders(*ListOrdersRequest, grpc.ServerStreamingServer[Order]) error
	// Client streaming: several request messages on one call.
	CreateOrders(grpc.ClientStreamingServer[Order, CreateOrdersSummary]) error
	// Answers with the requested status code and no body, which is the
	// trailers-only response that carries the status in the headers instead
	// of the trailers.
	Fail(context.Context, *FailRequest) (*Order, error)
	mustEmbedUnimplementedOrdersServer()
}

// UnimplementedOrdersServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrdersServer struct{}

func (UnimplementedOrdersServer) GetOrder(context.Context, *GetOrderRequest) (*Order, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedOrdersServer) ListOrders(*ListOrdersRequest, grpc.ServerStreamingServer[Order]) error {
	return status.Error(codes.Unimplemented, "method ListOrders not implemented")
}
func (UnimplementedOrdersServer) CreateOrders(grpc.ClientStreamingServer[Order, CreateOrdersSummary]) error {
	return status.Error(codes.Unimplemented, "method CreateOrders not implemented")
}
func (UnimplementedOrdersServer) Fail(context.Context, *FailRequest) (*Order, error) {
	return nil, status.Error(codes.Unimplemented, "method Fail not implemented")
}
func (UnimplementedOrdersServer) mustEmbedUnimplementedOrdersServer() {}
func (UnimplementedOrdersServer) testEmbeddedByValue()                {}

// UnsafeOrdersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrdersServer will
// result in compilation errors.
type UnsafeOrdersServer interface {
	mustEmbedUnimplementedOrdersServer()
}

func RegisterOrdersServer(s grpc.ServiceRegistrar, srv OrdersServer) {
	// If the following call panics, it indicates UnimplementedOrdersServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Orders_ServiceDesc, srv)
}

func _Orders_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdersServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orders_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdersServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orders_ListOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListOrdersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrdersServer).ListOrders(m, &grpc.GenericServerStream[ListOrdersRequest, Order]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Orders_ListOrdersServer = grpc.ServerStreamingServer[Order]

func _Orders_CreateOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrdersServer).CreateOrders(&grpc.GenericServerStream[Order, CreateOrdersSummary]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Orders_CreateOrdersServer = grpc.ClientStreamingServer[Order, CreateOrdersSummary]

func _Orders_Fail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdersServer).Fail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orders_Fail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdersServer).Fail(ctx, req.(*FailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Orders_ServiceDesc is the grpc.ServiceDesc for Orders service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Orders_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "demo.v1.Orders",
	HandlerType: (*OrdersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrder",
			Handler:    _Orders_GetOrder_Handler,
		},
		{
			MethodName: "Fail",
			Handler:    _Orders_Fail_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListOrders",
			Handler:       _Orders_ListOrders_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CreateOrders",
			Handler:       _Orders_CreateOrders_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "demo/v1/orders.proto",
}
