// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: demo/v1/orders.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_PENDING     Status = 1
	Status_STATUS_SHIPPED     Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_PENDING",
		2: "STATUS_SHIPPED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_PENDING":     1,
		"STATUS_SHIPPED":     2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_demo_v1_orders_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_demo_v1_orders_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_demo_v1_orders_proto_rawDescGZIP(), []int{0}
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_demo_v1_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_orders_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ListOrdersRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Limit    int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Customer string                 `protobuf:"bytes,2,opt,name=customer,proto3" json:"customer,omitempty"`
	// Pause between messages, so a stream can be observed arriving in pieces
	// rather than all at once.
	DelayMs       int32 `protobuf:"varint,3,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_demo_v1_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_orders_proto_rawDescGZIP(), []int{1}
}

func (x *ListOrdersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListOrdersRequest) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

func (x *ListOrdersRequest) GetDelayMs() int32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

type FailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A google.rpc.Code: 5 is NOT_FOUND, 7 PERMISSION_DENIED, 14 UNAVAILABLE.
	Code          int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailRequest) Reset() {
	*x = FailRequest{}
	mi := &file_demo_v1_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailRequest) ProtoMessage() {}

func (x *FailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailRequest.ProtoReflect.Descriptor instead.
func (*FailRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_orders_proto_rawDescGZIP(), []int{2}
}

func (x *FailRequest) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FailRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateOrdersSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       int32                  `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrdersSummary) Reset() {
	*x = CreateOrdersSummary{}
	mi := &file_demo_v1_orders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrdersSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrdersSummary) ProtoMessage() {}

func (x *CreateOrdersSummary) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_orders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrdersSummary.ProtoReflect.Descriptor instead.
func (*CreateOrdersSummary) Descriptor() ([]byte, []int) {
	return file_demo_v1_orders_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrdersSummary) GetCreated() int32 {
	if x != nil {
		return x.Created
	}
	return 0
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Customer      string                 `protobuf:"bytes,2,opt,name=customer,proto3" json:"customer,omitempty"`
	Lines         []*Line                `protobuf:"bytes,3,rep,name=lines,proto3" json:"lines,omitempty"`
	Total         *Money                 `protobuf:"bytes,4,opt,name=total,proto3" json:"total,omitempty"`
	Status        Status                 `protobuf:"varint,5,opt,name=status,proto3,enum=demo.v1.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_demo_v1_orders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_orders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_demo_v1_orders_proto_rawDescGZIP(), []int{4}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

func (x *Order) GetLines() []*Line {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *Order) GetTotal() *Money {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *Order) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

type Line struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         *Money                 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Line) Reset() {
	*x = Line{}
	mi := &file_demo_v1_orders_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Line) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Line) ProtoMessage() {}

func (x *Line) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_orders_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Line.ProtoReflect.Descriptor instead.
func (*Line) Descriptor() ([]byte, []int) {
	return file_demo_v1_orders_proto_rawDescGZIP(), []int{5}
}

func (x *Line) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Line) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Line) GetPrice() *Money {
	if x != nil {
		return x.Price
	}
	return nil
}

// int64 is deliberate: protojson renders it as a string, which is the kind of
// detail a decoder has to get right.
type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	AmountCents   int64                  `protobuf:"varint,2,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_demo_v1_orders_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_orders_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_demo_v1_orders_proto_rawDescGZIP(), []int{6}
}

func (x *Money) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Money) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

var File_demo_v1_orders_proto protoreflect.FileDescriptor

const file_demo_v1_orders_proto_rawDesc = "" +
	"\n" +
	"\x14demo/v1/orders.proto\x12\ademo.v1\",\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"`\n" +
	"\x11ListOrdersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x1a\n" +
	"\bcustomer\x18\x02 \x01(\tR\bcustomer\x12\x19\n" +
	"\bdelay_ms\x18\x03 \x01(\x05R\adelayMs\";\n" +
	"\vFailRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"/\n" +
	"\x13CreateOrdersSummary\x12\x18\n" +
	"\acreated\x18\x01 \x01(\x05R\acreated\"\xa7\x01\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bcustomer\x18\x02 \x01(\tR\bcustomer\x12#\n" +
	"\x05lines\x18\x03 \x03(\v2\r.demo.v1.LineR\x05lines\x12$\n" +
	"\x05total\x18\x04 \x01(\v2\x0e.demo.v1.MoneyR\x05total\x12'\n" +
	"\x06status\x18\x05 \x01(\x0e2\x0f.demo.v1.StatusR\x06status\"Z\n" +
	"\x04Line\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12$\n" +
	"\x05price\x18\x03 \x01(\v2\x0e.demo.v1.MoneyR\x05price\"F\n" +
	"\x05Money\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x12!\n" +
	"\famount_cents\x18\x02 \x01(\x03R\vamountCents*H\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x01\x12\x12\n" +
	"\x0eSTATUS_SHIPPED\x10\x022\xe8\x01\n" +
	"\x06Orders\x124\n" +
	"\bGetOrder\x12\x18.demo.v1.GetOrderRequest\x1a\x0e.demo.v1.Order\x12:\n" +
	"\n" +
	"ListOrders\x12\x1a.demo.v1.ListOrdersRequest\x1a\x0e.demo.v1.Order0\x01\x12>\n" +
	"\fCreateOrders\x12\x0e.demo.v1.Order\x1a\x1c.demo.v1.CreateOrdersSummary(\x01\x12,\n" +
	"\x04Fail\x12\x14.demo.v1.FailRequest\x1a\x0e.demo.v1.OrderB!Z\x1fsonda/examples/grpcdemo/demo/v1b\x06proto3"

var (
	file_demo_v1_orders_proto_rawDescOnce sync.Once
	file_demo_v1_orders_proto_rawDescData []byte
)

func file_demo_v1_orders_proto_rawDescGZIP() []byte {
	file_demo_v1_orders_proto_rawDescOnce.Do(func() {
		file_demo_v1_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_demo_v1_orders_proto_rawDesc), len(file_demo_v1_orders_proto_rawDesc)))
	})
	return file_demo_v1_orders_proto_rawDescData
}

var file_demo_v1_orders_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_demo_v1_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_demo_v1_orders_proto_goTypes = []any{
	(Status)(0),                 // 0: demo.v1.Status
	(*GetOrderRequest)(nil),     // 1: demo.v1.GetOrderRequest
	(*ListOrdersRequest)(nil),   // 2: demo.v1.ListOrdersRequest
	(*FailRequest)(nil),         // 3: demo.v1.FailRequest
	(*CreateOrdersSummary)(nil), // 4: demo.v1.CreateOrdersSummary
	(*Order)(nil),               // 5: demo.v1.Order
	(*Line)(nil),                // 6: demo.v1.Line
	(*Money)(nil),               // 7: demo.v1.Money
}
var file_demo_v1_orders_proto_depIdxs = []int32{
	6, // 0: demo.v1.Order.lines:type_name -> demo.v1.Line
	7, // 1: demo.v1.Order.total:type_name -> demo.v1.Money
	0, // 2: demo.v1.Order.status:type_name -> demo.v1.Status
	7, // 3: demo.v1.Line.price:type_name -> demo.v1.Money
	1, // 4: demo.v1.Orders.GetOrder:input_type -> demo.v1.GetOrderRequest
	2, // 5: demo.v1.Orders.ListOrders:input_type -> demo.v1.ListOrdersRequest
	5, // 6: demo.v1.Orders.CreateOrders:input_type -> demo.v1.Order
	3, // 7: demo.v1.Orders.Fail:input_type -> demo.v1.FailRequest
	5, // 8: demo.v1.Orders.GetOrder:output_type -> demo.v1.Order
	5, // 9: demo.v1.Orders.ListOrders:output_type -> demo.v1.Order
	4, // 10: demo.v1.Orders.CreateOrders:output_type -> demo.v1.CreateOrdersSummary
	5, // 11: demo.v1.Orders.Fail:output_type -> demo.v1.Order
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_demo_v1_orders_proto_init() }
func file_demo_v1_orders_proto_init() {
	if File_demo_v1_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_demo_v1_orders_proto_rawDesc), len(file_demo_v1_orders_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demo_v1_orders_proto_goTypes,
		DependencyIndexes: file_demo_v1_orders_proto_depIdxs,
		EnumInfos:         file_demo_v1_orders_proto_enumTypes,
		MessageInfos:      file_demo_v1_orders_proto_msgTypes,
	}.Build()
	File_demo_v1_orders_proto = out.File
	file_demo_v1_orders_proto_goTypes = nil
	file_demo_v1_orders_proto_depIdxs = nil
}
